<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Test Case Failed || Test Case ID: LoginPageTest.LoginTest()[pri:0, instance:com.qa.tests.LoginPageTest@59ec2012]]]>
    </line>
    <line>
      <![CDATA[Test Case Failed || Test Case ID: java.lang.AssertionError: expected [false] but found [true]]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="28966" started-at="2019-06-20T11:06:29Z" finished-at="2019-06-20T11:06:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28966" started-at="2019-06-20T11:06:29Z" finished-at="2019-06-20T11:06:58Z">
      <class name="com.qa.tests.LoginPageTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.qa.tests.LoginPageTest@59ec2012]" name="init" is-config="true" duration-ms="16048" started-at="2019-06-20T11:06:29Z" finished-at="2019-06-20T11:06:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="LoginTest()[pri:0, instance:com.qa.tests.LoginPageTest@59ec2012]" name="LoginTest" duration-ms="10752" started-at="2019-06-20T11:06:45Z" finished-at="2019-06-20T11:06:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.qa.tests.LoginPageTest.LoginTest(LoginPageTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.qa.tests.LoginPageTest@59ec2012]" name="tearDown" is-config="true" duration-ms="2067" started-at="2019-06-20T11:06:56Z" finished-at="2019-06-20T11:06:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTest status=FAILURE method=LoginPageTest.LoginTest()[pri:0, instance:com.qa.tests.LoginPageTest@59ec2012] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test Case Failed || Test Case ID: LoginPageTest.LoginTest()[pri:0, instance:com.qa.tests.LoginPageTest@59ec2012]]]>
            </line>
            <line>
              <![CDATA[Test Case Failed || Test Case ID: java.lang.AssertionError: expected [false] but found [true]]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.tests.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
